# Autogenerated wrapper script for COSMA_jll for x86_64-apple-darwin-mpi+openmpi
export cosma

using OpenBLAS_jll
using CompilerSupportLibraries_jll
using OpenMPI_jll
using MPIPreferences
JLLWrappers.@generate_wrapper_header("COSMA")
JLLWrappers.@declare_library_product(cosma, "@rpath/libcosma.dylib")
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS_jll, CompilerSupportLibraries_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        cosma,
        "lib/libcosma.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
